services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=${database_url}
      - RABBITMQ_URL=${RABBITMQ_URL}
    volumes:
      - images-data:/usr/src/app/images
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

volumes:
  images-data:
  db-data: