apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
  labels:
    app: detector
spec:
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
        - name: detector
          image: b4nd1/detect_facedetect:{{ .Values.env.DETECTOR_VERSION }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:15
          command: [ 'sh', '-c',
                     'until pg_isready -h db -p 5432; do echo waiting for database; sleep 2; done;' ]
      containers:
        - name: web
          image: b4nd1/webapp_facedetect:{{ .Values.env.APP_VERSION }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database_url
            - name: DETECTOR_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: detector_url
            - name: NTIFY_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ntify_url
          volumeMounts:
            - name: images-data
              mountPath: /usr/src/app/images
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: images-data
          persistentVolumeClaim:
            claimName: images-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-db
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntify
  labels:
    app: ntify
spec:
  selector:
    matchLabels:
      app: ntify
  template:
    metadata:
      labels:
        app: ntify
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:15
          command: [ 'sh', '-c',
                     'until pg_isready -h ntifydb -p 5432; do echo waiting for database; sleep 2; done;' ]
      containers:
        - name: ntify
          image: b4nd1/ntify_facedetect:{{ .Values.env.NTIFY_VERSION }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: NTFY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ntify_dburl
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: smtp_host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: smtp_port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: smtp_user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: smtp_pass
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: smtp_email_from
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntifydb
  labels:
    app: ntifydb
spec:
  selector:
    matchLabels:
      app: ntifydb
  template:
    metadata:
      labels:
        app: ntifydb
    spec:
      containers:
        - name: ntifydb
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-db
          volumeMounts:
            - name: ntifydb-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: ntifydb-data
          persistentVolumeClaim:
            claimName: ntifydb-pvc
