name: CD

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  WEB_IMAGE_NAME: webapp_facedetect
  DETECT_IMAGE_NAME: detect_facedetect

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build and push webapp Docker image
        run: |
          cd ./app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.WEB_IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.WEB_IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push detectapp Docker image
        run: |
          cd ./detector
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DETECT_IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DETECT_IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml
          sed -i 's|DETECTOR_VERSION:.*|DETECTOR_VERSION: '${{ github.sha }}'|' values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
